#jinja2: lstrip_blocks: True
{% for node_name, node_ip in nodes %}
---
schema: promenade/KubernetesNode/v1
metadata:
  schema: metadata/Document/v1
  name: {{ node_name }}
  layeringDefinition:
    abstract: false
    layer: site
  storagePolicy: cleartext
data:
  hostname: {{ node_name }}
  ip: {{ node_ip }}
  join_ip: {{ genesis.ip }}
  labels:
    dynamic:
{% for type, elt in types.items() %}
{% if node_name in elt['nodes'] %}
{% for label in elt['labels'] %}
      - {{ label }}
{% endfor %}
{% endif %}
{% endfor %}
{% endfor %}
...
