genesis:
  hostname: node01
  ip: 10.1.103.11
  mgmt_interface: ens3
script:
  user: kingsalamander
nodes:
  node01: 10.1.103.11
  node02: 10.1.103.12
  node03: 10.1.103.13

types:
  common:
    nodes:
      - node01
      - node02
      - node03
    labels:
      - calico-etcd=enabled
  openstack_compute:
    nodes:
      - node01
      - node02
      - node03
    labels:
      - openstack-compute-node=enabled
      - openvswitch=enabled
  openstack_control:
    nodes:
      - node01
      - node02
      - node03
    labels:
      - openstack-control-plane=enabled
      - openvswitch=enabled
  ceph_osd:
    nodes:
      - node01
      - node02
      - node03
    labels:
      - ceph-mds=enabled
      - ceph-mon=enabled
      - ceph-osd=enabled
      - ceph-rgw=enabled
      - ceph-mgr=enabled
  lma:
    nodes:
      - node01
      - node02
      - node03
    labels:
      - openstack-mon=enabled
  master:
    nodes:
      - node01
      - node02
      - node03
    labels:
      - kubernetes-scheduler=enabled
      - kubernetes-apiserver=enabled
      - kubernetes-etcd=enabled
      - kubernetes-controller-manager=enabled
      - kubernetes-scheduler=enabled
      - ucp-control-plane=enabled
