genesis:
  hostname: ceilometer01
  ip: 10.0.104.164
  mgmt_interface: ens2
nodes:
  osd01: 10.0.104.155
  osd02: 10.0.104.156
  osd03: 10.0.104.157
  mon01: 10.0.104.158
  mon02: 10.0.104.159
  mon03: 10.0.104.160
  cmp01: 10.0.104.161
  cmp02: 10.0.104.162
  cmp03: 10.0.104.163
  ceilometer01: 10.0.104.164
  journal01: 10.0.104.167
  journal02: 10.0.104.168
  journal03: 10.0.104.169

types:
  common:
    nodes:
      - osd01
      - osd02
      - osd03
      - mon01
      - mon02
      - mon03
      - cmp01
      - cmp02
      - cmp03
      - ceilometer01
      - journal01
      - journal02
      - journal03
    labels:
      - calico-etcd=enabled
  openstack:
    nodes:
      - ctl01
      - ctl02
      - ctl03
      - cmp01
      - cmp02
      - cmp03
      - journal01
      - journal02
      - journal03
    labels:
      - openstack-control-plane=enabled
      - openstack-compute-node=enabled
      - openvswitch=enabled
  ceph_osd:
    nodes:
      - osd01
      - osd02
      - osd03
    labels:
      - ceph-mds=enabled
      - ceph-mon=enabled
      - ceph-osd=enabled
      - ceph-rgw=enabled
      - ceph-mgr=enabled
  lma:
    nodes:
      - mon01
      - mon02
      - mon03
    labels:
      - openstack-mon
  master:
    nodes:
      - ceilometer01
      - journal01
      - journal02
      - journal03
    labels:
      - kubernetes-scheduler=enabled
      - kubernetes-apiserver=enabled
      - kubernetes-etcd=enabled
      - kubernetes-controller-manager=enabled
      - kubernetes-scheduler=enabled
      - ucp-control-plane=enabled
