genesis:
  hostname: ctl01
  ip: 10.0.104.151
  mgmt_interface: ens2
nodes:
  ctl01: 10.0.104.151
  ctl02: 10.0.104.152
  ctl03: 10.0.104.153

types:
  common:
    nodes:
      - ctl01
      - ctl02
      - ctl03
    labels:
      - calico-etcd=enabled
  ceph_osd:
    nodes:
      - ctl01
      - ctl02
      - ctl03
    labels:
      - ceph-mds=enabled
      - ceph-mon=enabled
      - ceph-osd=enabled
      - ceph-rgw=enabled
      - ceph-mgr=enabled
  master:
    nodes:
      - ctl01
      - ctl02
      - ctl03
    labels:
      - kubernetes-scheduler=enabled
      - kubernetes-apiserver=enabled
      - kubernetes-etcd=enabled
      - kubernetes-controller-manager=enabled
      - kubernetes-scheduler=enabled
      - ucp-control-plane=enabled
