genesis:
  mtu: 1500
  hostname: cfg01
  ip: 10.1.103.10
  mgmt_interface: ens3
  join_ip: 10.1.103.11
  #external_ip: EXTERNAL_IP
docker:
  registries:
    - 10.1.103.20:5000
    - registry2:5000
    - registry3:5000
    - registry4:5000
  #bip: 172.17.0.0/16
script:
  enabled: True
  user: kingsalamander
  key_file: /root/.ssh/id_rsa
nodes:
  cfg01: 10.1.103.10
  ctl01: 10.1.103.11
  ctl02: 10.1.103.12
  ctl03: 10.1.103.13

provisioner:
  type: ceph 

types:
  common:
    nodes:
      - cfg01
      - ctl01
      - ctl02
      - ctl03
    labels:
      - calico-etcd=enabled
  openstack_compute:
    nodes:
      - ctl01
      - ctl02
      - ctl03
    labels:
      - openstack-compute-node=enabled
      - openvswitch=enabled
  openstack_control:
    nodes:
      - cfg01
      - ctl01
      - ctl02
      - ctl03
    labels:
      - openstack-control-plane=enabled
      - openvswitch=enabled
  ceph_osd:
    nodes:
      - ctl01
      - ctl02
      - ctl03
    labels:
      - ceph-mds=enabled
      - ceph-mon=enabled
      - ceph-osd=enabled
      - ceph-rgw=enabled
      - ceph-mgr=enabled
  lma:
    nodes:
      - cfg01
      - ctl01
      - ctl02
      - ctl03
    labels:
      - openstack-mon=enabled
  master:
    nodes:
      - ctl01
      - ctl02
      - ctl03
      - cfg01
    labels:
      - kubernetes-scheduler=enabled
      - kubernetes-apiserver=enabled
      - kubernetes-etcd=enabled
      - kubernetes-controller-manager=enabled
      - kubernetes-scheduler=enabled
      - ucp-control-plane=enabled
      - coredns=enabled
